version: "1"
module_version: 1.0.1

tests:
  - name: With older TF
    id: oldtf1
    terraform_version: 1.0.11
    before_init: ["exit 1"]

  - name: Newer TF 1
    id: newtf1
    depends_on: ["oldtf1"]
    terraform_version: 1.1.1
